### PR TITLE
Add some tests

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request adds some tests.

Specifically, we run `Vimes.go` on JSON several times with different values for the various keyword arguments.

### CODE REVIEW

**Comment by MikeInnes** [comment]
I was thinking that for testing this we should probably have some fake mini-project in the tests folder, maybe with a small code file in, and make sure that certain diffs get found by Vimes. This works well too for now.

Of course ideally we should run Vimes on itself and write test cases that way :)

**Comment by DilumAluthge** [comment]
> I was thinking that for testing this we should probably have some fake mini-project in the tests folder, maybe with a small code file in, and make sure that certain diffs get found by Vimes. This works well too for now.

That's a good idea, and we should do that as well.

> Of course ideally we should run Vimes on itself and write test cases that way :)

I actually thought about doing that! But if we run Vimes on itself, and if the test suite for Vimes includes running Vimes on itself.... won't that keep happening recursively forever? Presumably we'd need a way to detect and prevent that.

**Comment by MikeInnes** [comment]
Yeah, I don't mean run Vimes on itself as part of the test suite, just to do it by hand in order to come up test case inspiration (which is really how it's designed to be used generally).

Running Vimes as part of CI would be interesting, but it might be hard to guarantee that it doesn't come up with anything spurious; I guess we'll have to see what that looks like in practice as things mature.

**Comment by DilumAluthge** [comment]
> Yeah, I don't mean run Vimes on itself as part of the test suite, just to do it by hand in order to come up test case inspiration (which is really how it's designed to be used generally).

Ahhhh, yes, that makes much more sense. Yes we should do that.

**Pull request merged**
