### PR TITLE
Looser compat bounds

### PR DESCRIPTION
**Pull request by MikeInnes**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
The hyphen syntax has not been implemented yet. See https://github.com/JuliaLang/Pkg.jl/pull/1410

**Comment by DilumAluthge** [comment]
StatsBase before 0.25 does not support Julia 1.0, so we are only compatible with StatsBase 0.25 to StatsBase 0.34.

**Comment by MikeInnes** [comment]
Huh, could've sworn I'd used that somewhere, but I guess it was in the registry rather than in a package project.toml.

**Comment by DilumAluthge** [comment]
> Huh, could've sworn I'd used that somewhere, but I guess it was in the registry rather than in a package project.toml.

Yeah you can use hyphen syntax in the registry. But not yet in Project files.

**Pull request merged**
