### PR TITLE
Pin MacroTools to 0.5.1

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Perhaps just change the dependency to MacroTools + SourceWalk?

**Comment by DilumAluthge** [comment]
Makes sense. What would be the minimum version of MacroTools and the minimum version of SourceWalk?

**Comment by DilumAluthge** [comment]
@MikeInnes Also:

In MacroTools 0.5.1, there is a vendored copy of CSTParser: https://github.com/MikeInnes/MacroTools.jl/tree/v0.5.1/src/cstparser

That seems to be gone in MacroTools 0.5.2.

If I am not mistaken, Vimes relies on the CSTParser vendored inside MacroTools, right?

**Comment by DilumAluthge** [comment]
Never mind, it looks like the vendored CSTParser is inside SourceWalk now.

**Comment by DilumAluthge** [comment]
Closing in favor of #23

**Pull request closed without merging**
